/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
 * DO NOT EDIT THIS FILE!! 
 * 
 *  TO CUSTOMIZE Infrastructure.js PLEASE EDIT ../custom/InfrastructureCustom.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */
const app = require('../../app.js');
const db_vcenterws_db = require('../../db/vcenterws_db_schema.js')
const properties = require('../../properties.js');
const handleError = require('../../security/util.js').handleError;
require('./custom/InfrastructureCustom.js');

/*
 * SCHEMA DB Infrastructure
 * 
	{
		release: {
			type: 'String'
		},
		vc: {
			type: 'String'
		},
		//RELATIONS
		
		
		//EXTERNAL RELATIONS
		
		infrastructure: [{
			type: Schema.ObjectId,
			ref : "User"
		}],
		user: [{
			type: Schema.ObjectId,
			ref : "Infrastructure"
		}],
		
	}
 * 
 */



//CRUD METHODS


/**
 * InfrastructureService.create
 *   @description CRUD ACTION create
 *
 */
app.post(properties.api + '/infrastructures', function (req, res) {
	obj = new db_vcenterws_db.Infrastructure(req.body);
	obj.save(function (err) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * InfrastructureService.delete
 *   @description CRUD ACTION delete
 *   @param ObjectId id Id
 *
 */
app['delete'](properties.api + '/infrastructures/:id', function (req, res) {
	db_vcenterws_db.Infrastructure.findByIdAndRemove(req.params.id, function (err) {
		  if (err) return handleError(err, res);
		  res.send(err);
	});
});

/**
 * InfrastructureService.findByuser
 *   @description CRUD ACTION findByuser
 *   @param Objectid key Id della risorsa user da cercare
 *
 */
app.get(properties.api + '/infrastructures/findByuser/:key', function (req, res) {

	db_vcenterws_db.Infrastructure.find({ 'user' : req.params.key}).exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
	
});

/**
 * InfrastructureService.get
 *   @description CRUD ACTION get
 *   @param ObjectId id Id 
 *
 */
app.get(properties.api + '/infrastructures/:id', function (req, res) {
	db_vcenterws_db.Infrastructure.findOne({_id:req.params.id}).exec(function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * InfrastructureService.list
 *   @description CRUD ACTION list
 *
 */
app.get(properties.api + '/infrastructures', function (req, res) {
	db_vcenterws_db.Infrastructure.find().exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
});

/**
 * InfrastructureService.update
 *   @description CRUD ACTION update
 *   @param ObjectId id Id
 *
 */
app.post(properties.api + '/infrastructures/:id', function (req, res) {
	db_vcenterws_db.Infrastructure.findByIdAndUpdate(req.params.id, req.body, {'new': true}, function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});


/*
 * CUSTOM SERVICES
 * 
 *	These services will be overwritten and implemented in  Custom.js
 */

