# Docker-compose version
version: '2'

# Define the services/containers to be run
services:

  # Service name
  app: 
    # directory of Dockerfile
    build: ./ 
    ports:
      - "3000:3000"
    # link this service to database service
    volumes:
      - '/home/jan/sk-vcenter/vcenterws:/app'
    links:
      - "database:db"

  # Database service name
  database:
    # image to build container from
    image: mongo 
    ports:
      - "27018:27017"