/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE executionBaseService PLEASE EDIT ../execution.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Execution } from '../../domain/vcenterws_db/execution';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Execution.service.ts
 */

/*
 * SCHEMA DB Execution
 *
	{
		//RELATIONS
		//EXTERNAL RELATIONS
		Script: {
			type: Schema.ObjectId,
			ref : "Execution"
		},
		user: {
			type: Schema.ObjectId,
			ref : "Execution"
		},
	}
 *
 */
@Injectable()
export class ExecutionBaseService {

    contextUrl: string = environment.endpoint + '/executions';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ExecutionService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Execution): Observable<Execution> {
        return this.http
            .post<Execution>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ExecutionService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ExecutionService.findByScript
    *   @description CRUD ACTION findByScript
    *   @param Objectid key Id della risorsa Script da cercare
    *
    */
    findByScript(id: string): Observable<Execution[]> {
        return this.http
            .get<Execution[]>(this.contextUrl + '/findByScript/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExecutionService.findByuser
    *   @description CRUD ACTION findByuser
    *   @param Objectid key Id della risorsa user da cercare
    *
    */
    findByUser(id: string): Observable<Execution[]> {
        return this.http
            .get<Execution[]>(this.contextUrl + '/findByUser/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExecutionService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Execution> {
        return this.http
            .get<Execution>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ExecutionService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Execution[]> {
        return this.http
            .get<Execution[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ExecutionService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Execution): Observable<Execution> {
        return this.http
            .post<Execution>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
