/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE infrastructureBaseService PLEASE EDIT ../infrastructure.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Infrastructure } from '../../domain/vcenterws_db/infrastructure';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Infrastructure.service.ts
 */

/*
 * SCHEMA DB Infrastructure
 *
	{
		release: {
			type: 'String'
		},
		vc: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		infrastructure: [{
			type: Schema.ObjectId,
			ref : "User"
		}],
		user: [{
			type: Schema.ObjectId,
			ref : "Infrastructure"
		}],
	}
 *
 */
@Injectable()
export class InfrastructureBaseService {

    contextUrl: string = environment.endpoint + '/infrastructures';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * InfrastructureService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Infrastructure): Observable<Infrastructure> {
        return this.http
            .post<Infrastructure>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * InfrastructureService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * InfrastructureService.findByuser
    *   @description CRUD ACTION findByuser
    *   @param Objectid key Id della risorsa user da cercare
    *
    */
    findByUser(id: string): Observable<Infrastructure[]> {
        return this.http
            .get<Infrastructure[]>(this.contextUrl + '/findByUser/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * InfrastructureService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Infrastructure> {
        return this.http
            .get<Infrastructure>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * InfrastructureService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Infrastructure[]> {
        return this.http
            .get<Infrastructure[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * InfrastructureService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Infrastructure): Observable<Infrastructure> {
        return this.http
            .post<Infrastructure>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
